name: animated_scrollable_timeline

packages:
  - .

scripts:
  analyze:
    run: |
      melos exec -c 1 -- \
        flutter analyze .
    description: Run `flutter analyze` for all packages

  test:
    run: |
      melos exec -c 1 -- \
        flutter test
    description: Run `flutter test` for all packages

  version:
    run: |
      melos version --yes
    description: Version all packages

  publish:
    run: |
      melos publish --yes
    description: Publish all packages

  clean:
    run: |
      melos clean
    description: Clean all packages