name: animated_scrollable_timeline
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/bitswar.git
repository: https://github.com/bitswar/animated_scrollable_timeline.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
