name: animated_scrollable_timeline
description: Flutter plugin which provides infinity scrollable timeline widget. It can be useful for implementing real-time streaming components as timeline for playing video.

version: 1.0.1
homepage: https://github.com/bitswar
repository: https://github.com/bitswar/animated_scrollable_timeline.git

false_secrets:
  - example/**

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
